### ISSUE TITLE
Import failed because of unfound movies

### ISSUE THREAD

**Issue by vavelsky** [tomzx/imdb-importer#8]
Has anything changed on imdb that can't find a movies? I've tried multiple times on different titles with no success.
What should I change to make it work?

Here you have what I got with movie called "Project Nim":
```
Searching for Project Nim

Warning: file_get_contents(http://www.imdb.com/xml/find?json=1&nr=1&tt=on&q=Project+Nim): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found
 in /.../Composer/imdb-importer/src/ImdbImporter/Importer.php on line 119

Fatal error: Uncaught Exception: Error while fetching tconst for Project Nim. in /.../Composer/imdb-importer/src/ImdbImporter/Importer.php:122
Stack trace:
#0 /.../Composer/imdb-importer/src/ImdbImporter/Importer.php(63): ImdbImporter\Importer->getIdByTitle('Project Nim')
#1 /.../Composer/imdb-importer/runme.php(11): ImdbImporter\Importer->submit(Array)
#2 {main}
  thrown in /.../Composer/imdb-importer/src/ImdbImporter/Importer.php on line 122

**Comment by shatner** [comment]
IMDb has been pushing out a site-wide redesign, with a new structure for pages and some new behaviors (e.g., visiting the main IMDb page for a film now redirects to a “reference” page in some cases—enter http://www.imdb.com/title/tt1590193/ in s browser and get http://www.imdb.com/title/tt1590193/reference for instance).

Similar scripts for fetching information from IMDb have also been failing since this redesign. It’s unclear whether IMDb is intentionally shutting down the pathways being used to fetch information, or if the redesign has brought changes that will require the information to be fetched in a slightly different way. 

An example of another affected project: https://github.com/yswery/PHP-IMDB-API/

**Comment by tomzx** [comment]
I've pushed 9ac337f947d625df98669290bf286b7ca1431beb which should fix this issue. Can you both give it a try and let me know if it works fine for you? I'll make a release afterward.

**Comment by vavelsky** [comment]
Thank you for fixing so quickly. Actually now I got a 400 Bad Request in the same place
```
Searching for Project Nim

Warning: file_get_contents(https://v2.sg.media-imdb.com/suggests/P/Project+Nim.json): failed to open stream: HTTP request failed! HTTP/1.1 400 Bad Request
 in /.../Composer/imdb-importer/src/ImdbImporter/Importer.php on line 120

Fatal error: Uncaught Exception: Error while fetching tconst for Project Nim. in /.../Composer/imdb-importer/src/ImdbImporter/Importer.php:124
Stack trace:
#0 /.../Composer/imdb-importer/src/ImdbImporter/Importer.php(63): ImdbImporter\Importer->getIdByTitle('Project Nim')
#1 /.../Composer/imdb-importer/runme.php(11): ImdbImporter\Importer->submit(Array)
#2 {main}
  thrown in /.../Composer/imdb-importer/src/ImdbImporter/Importer.php on line 124

**Comment by tomzx** [comment]
Alright I see. I forgot to lowercase the results. Furthermore, it appears that IMDb also does convert accented characters into non-accented characters. It seems it should be formatted as a valid function name as the query will be used as part of the javascript function name. However, I didn't go as far as stripping all the invalid characters. I'll see what I can do about that another day.

**Comment by vavelsky** [comment]
Fixes work fine now.
